name: flutter_fancy_tree_view
description: >
  A highly customizable TreeView Widget for visualization of nested data in
  Flutter.
version: 0.5.1+1
homepage: https://mbaumgartenbr.github.io/flutter_tree_view
repository: https://github.com/mbaumgartenbr/flutter_tree_view

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: "2.0.1"
  flutter_test:
    sdk: flutter
